# Generated by Django 3.2.9 on 2022-03-10 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0002_rename_survey_choice_survey_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='survey_collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.survey_collection'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('image', 'user', 'survey_collection')},
        ),
    ]
