# Generated by Django 3.2.9 on 2022-06-28 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0002_alter_image_collection_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Transformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_transformation', models.CharField(max_length=200)),
                ('image_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.image_collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('image_collection', 'user')},
            },
        ),
    ]
