# Generated by Django 3.2.9 on 2022-06-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_image_transformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_collection',
            name='transformations',
            field=models.CharField(default='', max_length=200),
        ),
    ]
