# Generated by Django 3.2.9 on 2022-03-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20220310_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
