# Generated by Django 3.2.9 on 2022-06-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_survey_collection_transformations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_collection',
            name='transformation',
        ),
    ]
